name: Release binaries

on:
  release:
    types: [published]

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.83.0
          override: true
          target: x86_64-unknown-linux-gnu

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y pkg-config libssl-dev libpq-dev gcc protobuf-compiler

      - name: Build binary
        run: |
          RUSTFLAGS="-C target-feature=-crt-static -C link-args=-s" \
          cargo build --release --target x86_64-unknown-linux-gnu

      - name: Compress binary
        run: gzip target/x86_64-unknown-linux-musl/release/simply-kaspa-indexer

      - name: Upload release asset
        uses: softprops/action-gh-release@v1
        with:
          files: target/x86_64-unknown-linux-musl/release/simply-kaspa-indexer.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
